"""Strategy Engine - high-level business strategy and decision-making.

Synthesizes data from all business modules to recommend strategic
actions and prioritize what the agent should focus on next.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field

from sovereign.config import SovereignConfig


class GoalStatus(str, Enum):
    ACTIVE = "active"
    ACHIEVED = "achieved"
    PAUSED = "paused"
    ABANDONED = "abandoned"


class GoalPriority(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class BusinessGoal(BaseModel):
    """A strategic business goal."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    description: str
    priority: GoalPriority = GoalPriority.MEDIUM
    status: GoalStatus = GoalStatus.ACTIVE
    target_metric: str = ""
    target_value: float = 0.0
    current_value: float = 0.0
    deadline: datetime | None = None
    milestones: list[dict[str, Any]] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def progress_pct(self) -> float:
        if self.target_value <= 0:
            return 0.0
        return min((self.current_value / self.target_value) * 100, 100.0)


class StrategyRecommendation(BaseModel):
    """A strategic recommendation generated by the engine."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    description: str
    priority: GoalPriority = GoalPriority.MEDIUM
    category: str = ""  # growth, retention, cost_optimization, etc.
    expected_impact: str = ""
    effort_estimate: str = ""  # low, medium, high
    related_goals: list[str] = Field(default_factory=list)
    action_items: list[str] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class StrategyEngine:
    """High-level business strategy engine.

    Analyzes data from all business modules and generates strategic
    recommendations for what the agent should prioritize.

    Features:
    - Goal tracking and progress monitoring
    - Strategic recommendation generation
    - Priority-based action planning
    - Market opportunity identification
    - Risk assessment
    """

    def __init__(self, config: SovereignConfig) -> None:
        self.config = config
        self._goals: dict[str, BusinessGoal] = {}
        self._recommendations: list[StrategyRecommendation] = []

    def add_goal(self, goal: BusinessGoal) -> BusinessGoal:
        """Add a business goal."""
        self._goals[goal.id] = goal
        return goal

    def update_goal_progress(
        self, goal_id: str, current_value: float
    ) -> BusinessGoal | None:
        """Update progress on a goal."""
        goal = self._goals.get(goal_id)
        if not goal:
            return None
        goal.current_value = current_value
        if goal.current_value >= goal.target_value:
            goal.status = GoalStatus.ACHIEVED
        return goal

    def get_active_goals(self) -> list[BusinessGoal]:
        """Get all active goals sorted by priority."""
        priority_order = {
            GoalPriority.CRITICAL: 0,
            GoalPriority.HIGH: 1,
            GoalPriority.MEDIUM: 2,
            GoalPriority.LOW: 3,
        }
        active = [g for g in self._goals.values() if g.status == GoalStatus.ACTIVE]
        return sorted(active, key=lambda g: priority_order.get(g.priority, 4))

    def generate_recommendations(
        self,
        analytics_data: dict[str, Any] | None = None,
        lead_data: dict[str, Any] | None = None,
        finance_data: dict[str, Any] | None = None,
        revenue_data: dict[str, Any] | None = None,
    ) -> list[StrategyRecommendation]:
        """Generate strategic recommendations based on current business state.

        Analyzes all available data to identify:
        - Growth opportunities
        - Cost optimization areas
        - Revenue risks
        - Market gaps
        """
        recommendations: list[StrategyRecommendation] = []

        # Revenue recommendations
        if revenue_data:
            growth_rate = revenue_data.get("growth_rate_pct", 0)
            if growth_rate < 0:
                recommendations.append(
                    StrategyRecommendation(
                        title="Revenue Declining - Immediate Action Required",
                        description=f"Revenue growth rate is {growth_rate:.1f}%. Focus on retention and new acquisition.",
                        priority=GoalPriority.CRITICAL,
                        category="growth",
                        expected_impact="Stabilize revenue decline",
                        effort_estimate="high",
                        action_items=[
                            "Analyze customer churn reasons",
                            "Launch retention campaign",
                            "Identify new revenue opportunities",
                            "Review pricing strategy",
                        ],
                    )
                )
            elif growth_rate < 10:
                recommendations.append(
                    StrategyRecommendation(
                        title="Accelerate Revenue Growth",
                        description="Revenue growth is modest. Consider expanding marketing and outreach.",
                        priority=GoalPriority.HIGH,
                        category="growth",
                        expected_impact="Increase growth rate to 20%+",
                        effort_estimate="medium",
                        action_items=[
                            "Increase content output",
                            "Expand lead generation channels",
                            "Test new pricing tiers",
                        ],
                    )
                )

        # Lead pipeline recommendations
        if lead_data:
            conversion_rate = lead_data.get("conversion_rate", 0)
            total_leads = lead_data.get("total_leads", 0)

            if total_leads < 10:
                recommendations.append(
                    StrategyRecommendation(
                        title="Expand Lead Pipeline",
                        description=f"Only {total_leads} leads in pipeline. Need more top-of-funnel activity.",
                        priority=GoalPriority.HIGH,
                        category="growth",
                        expected_impact="10x lead volume",
                        effort_estimate="medium",
                        action_items=[
                            "Launch web scraping for prospects",
                            "Create lead magnets (free tools, guides)",
                            "Start cold outreach campaign",
                            "Optimize SEO for inbound leads",
                        ],
                    )
                )

            if conversion_rate < 0.1 and total_leads > 20:
                recommendations.append(
                    StrategyRecommendation(
                        title="Improve Lead Conversion Rate",
                        description=f"Conversion rate is {conversion_rate:.1%}. Focus on qualification and nurturing.",
                        priority=GoalPriority.HIGH,
                        category="retention",
                        expected_impact="Double conversion rate",
                        effort_estimate="medium",
                        action_items=[
                            "Review lead scoring criteria",
                            "Improve follow-up sequences",
                            "Create case studies and social proof",
                        ],
                    )
                )

        # Finance recommendations
        if finance_data:
            net_profit = finance_data.get("net_profit_usd", 0)
            if net_profit < 0:
                recommendations.append(
                    StrategyRecommendation(
                        title="Path to Profitability",
                        description=f"Currently losing ${abs(net_profit):.2f}. Need to reduce costs or increase revenue.",
                        priority=GoalPriority.CRITICAL,
                        category="cost_optimization",
                        expected_impact="Achieve profitability",
                        effort_estimate="high",
                        action_items=[
                            "Audit LLM API costs and optimize model routing",
                            "Identify and cut non-essential expenses",
                            "Focus on highest-ROI revenue activities",
                        ],
                    )
                )

        # Goal-based recommendations
        for goal in self.get_active_goals():
            if goal.progress_pct < 25 and goal.priority in (GoalPriority.CRITICAL, GoalPriority.HIGH):
                recommendations.append(
                    StrategyRecommendation(
                        title=f"Goal Behind Schedule: {goal.name}",
                        description=f"Only {goal.progress_pct:.0f}% progress on high-priority goal.",
                        priority=goal.priority,
                        category="execution",
                        expected_impact="Get back on track",
                        effort_estimate="medium",
                        related_goals=[goal.id],
                        action_items=[
                            f"Reassess approach for: {goal.name}",
                            "Allocate more agent resources",
                            "Break into smaller milestones",
                        ],
                    )
                )

        self._recommendations = recommendations
        return recommendations

    def get_next_actions(self, max_actions: int = 5) -> list[str]:
        """Get the most important actions to take right now.

        Synthesizes goals and recommendations into a prioritized action list.
        """
        actions: list[tuple[int, str]] = []
        priority_scores = {
            GoalPriority.CRITICAL: 0,
            GoalPriority.HIGH: 1,
            GoalPriority.MEDIUM: 2,
            GoalPriority.LOW: 3,
        }

        for rec in self._recommendations:
            score = priority_scores.get(rec.priority, 4)
            for action in rec.action_items:
                actions.append((score, action))

        actions.sort(key=lambda x: x[0])
        return [action for _, action in actions[:max_actions]]
